  version: '3.8'

  services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: library
        POSTGRES_USER: ysykal
        POSTGRES_PASSWORD: password
      networks:
        - shared-network
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: yurasykal@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
      networks:
        - shared-network
      ports:
        - "5050:80"
      depends_on:
        - postgres

  volumes:
    postgres_data:

  networks:
    shared-network:
      external: true